name: Deploy to EC2

on:
  push:
    branches:
      - main   # change if needed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/github-ec2
          chmod 600 ~/.ssh/github-ec2
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github-ec2 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            APP_DIR="/home/ubuntu/whitepenguin/frontend"
            REPO="https://mac:${{ secrets.GH_PAT }}@github.com/heimdallinc/whitepenguin.git"

            if [ ! -d "$APP_DIR/.git" ]; then
              echo "Cloning fresh repository..."
              rm -rf "$APP_DIR"
              mkdir -p /home/ubuntu/whitepenguin
              git clone "$REPO" "$APP_DIR"
            else
              echo "Pulling latest changes..."
              cd "$APP_DIR"
              git reset --hard
              git clean -fd
              git pull origin main
            fi

            cd "$APP_DIR"

            npm ci --legacy-peer-deps
            echo "Setting environment variables..."
            cat > .env <<EOT
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOT
            npm run build
            pm2 start next start --name whitepenguin-app
          EOF
